### ISSUE TITLE
Improvement: option to disable html formatting

### ISSUE THREAD

**Issue by sandersantema** [c-okelly/org_to_anki#28]
It would be nice to have an option to disable formatting. 

For instance, you'd have the following in your org file:
```
# type=Basic
# formatting=false
* Question
** Answer
```

Which would result in the following card being generated:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/21057514/55881998-06e5d300-5ba4-11e9-87c8-75bc013e3ed8.png">

Instead of:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/21057514/55881963-f170a900-5ba3-11e9-9b4a-c4fc22cd065e.png">

**Comment by sandersantema** [comment]
What might be a better overall solution (I think at least more versatile) is to break up the commandline tool in a converter and importer, where the converter would output to ```stdout``` and the importer would take input from ```stdin``` allowing for usage of for instance ```sed``` in between. Say for instance you don't want the answer formatted as a bullet point list and ```ota``` would be shorthand for ```org_to_anki``` then the command would be:

```ota -o <file> | sed 's/\<li\>//g' | sed 's/\<\/li\>//g' | ota -i```

The sed part could probably be done with one command but I hope you get the idea.

**Comment by c-okelly** [comment]
I get your line of thinking but I don't really think it fit in with the way I see the application evolving long term tbh. I kinda like the idea of being able to specify everything in the markdown of the document with default options as they currently are. The benefit of this would be that the same file should always parse to the same result.

When you convert the list of question answers to format them for Anki you need to format the as an html list. Remove the `<li>` tags in this case would end up just leaving you with a badly formatted HTML list.

This enhancement overall isn't really that complicated to do but I'm not sure when I can actually finish it but should be much quicker then #27. That one will require a bit of refactoring and test updating!

**Comment by c-okelly** [comment]
@sandersantema just an update. Won't make any progress on either issue till next weekend but will finish them then!

**Comment by sandersantema** [comment]
No hurry!

**Comment by c-okelly** [comment]
@sandersantema 

I decided to go with `list` instead `formatting` as it was slightly less generic for the list usecase

I'm already regretting using `type` instead of `noteType` but would prefer to avoid breaking changes at this point.

closed by #31
