### ISSUE TITLE
About org files

### ISSUE THREAD

**Issue by tianshanghong** [c-okelly/org_to_anki#3]
Hi, there. I noticed the PR in [Add org_to_anki GitHub link #8](https://github.com/tianshanghong/awesome-anki/pull/8). However, I'm quite misunderstood about this tool, especially what the ".org" file is for. I have a humble suggestion, why not add a little more description in [README.md](https://github.com/c-okelly/org_to_anki/blob/master/README.md) file of your project, so that even new users like me can easily tell what this tool is all about. Thanks!

**Comment by c-okelly** [comment]
Hey, that is a very fair point. I had written the readme expecting / project would already know what an org files is. I will add the information to the readme to better explain what it is. 

Thanks for the suggestion!

**Comment by tianshanghong** [comment]
@c-okelly Interesting! I think that's enough. :)
