### ISSUE TITLE
Exports Defaults to Subdeck beneath "0. List Notes" Deck

### ISSUE THREAD

**Issue by coltmay** [c-okelly/org_to_anki#57]
I am on Windows exporting from org files.  When I export, a correctly named subdeck is created beneath deck "0. List Notes".

I'm sure I'm missing something obvious, but how do I prevent the creation of this top level deck?

Thank you for your time and for this project.  It's incredibly helpful.

**Comment by c-okelly** [comment]
Hey,

Apologies for the delay in getting back to you. Currently there is not support for doing this though it should be possible. I will reopen this issues toe track it as a feature

**Comment by c-okelly** [comment]
Apologies I have been super busy in the last 2 months but hopefully it'll start to quiet down towards the end of this month!

**Comment by coltmay** [comment]
Thanks very much!  You're too kind.

**Comment by c-okelly** [comment]
Should be fixed by #58 . Though this touches part of the integration code that is not well tested to I am a bit wary. Are you using the cli version of the build in version by the way?

**Comment by coltmay** [comment]
Thanks much!  I'm using the Plugin version.

**Comment by c-okelly** [comment]
updated and manually tested
