### ISSUE TITLE
[idea] assign LibreOffice Writer list styles to Anki fields

### ISSUE THREAD

**Issue by omega3** [c-okelly/org_to_anki#60]
Would it be possible to introduce this feature: assign LibreOffice Writer lists styles to Anki fields?

In Writer you can use lists styles or create your own styles and using them is easy. For each line I wish I could use different list style, so that when importing in Anki each style would go to different field. This would allow to create multi-field notes in Writer.

Add-on would have to have configuration file to define which style goes to which field.

Another idea would be to use paragraph styles so that add on would match each style to different field. 
The easiest way to style is to use Bold, Italic, Underline, Cross-out or text colors.

This would make work very easy because for a long list of content user could use  Writer's format painter icon to quickly format multiple lines or in more advanced cases find and replace feature to format lines of text (Alt find and replace LO add-on).

**Comment by c-okelly** [comment]
Could you send me on some example documents of what you would expect it to look like?

There is functionally to define each line as a specifically named field. It's under the org documentation rather then the docs one. 

Not sure if that would meet your use case though

**Comment by omega3** [comment]
I was wondering if there is any faster way than using asterisks. 

For example, I copy to Writer content of dictionary 
https://www.wordreference.com/enpl/become
as unformatted text, remove tabs (with Alt Find & Replace add-on) and now I have a task to make notes from it. Using asterisks for a view hundred lines of text is daunting and time consuming. I was wondering if there is any easier way, a way that can use mouse clicks. But I saved Writer's page as html and I don't see any pattern of code, any html signs that refers to numbered list. But Writer saves in its html <b> <i> <u> <strike>.
Perhaps this could be used as a field reference?
Sample text:
https://i.imgur.com/BnoeDhf.png

https://drive.google.com/file/d/1aD7U6Mew9GdpIm0d4wh022pS1e7kZgGi/view?usp=sharing


Maybe other text / html editors would be more suitable for this task - I don't know. But highlighting a sentence and press icon of Bold, Italic, Underline, Cross out is more convenient and faster than typing asterisks.

**Comment by omega3** [comment]
Maybe using some markdown editor would be a better idea than using Writer.

Some developers already try link markdown note taking apps with creating Anki cards
https://www.reddit.com/r/TiddlyWiki5/comments/il697i/tiddly_research_roam_research_remnote_alternative/

https://www.reddit.com/r/ObsidianMD/comments/imcwk8/obsidian_to_anki_a_featurerich_script_that_allows/
