### ISSUE TITLE
How to add an image to Extra field of Cloze?

### ISSUE THREAD

**Issue by michaelsjackson** [c-okelly/org_to_anki#69]
Tried, did not work here. Do you have any working example?  Thanks in advance.  Adding an image on a basic note is working here, but not in Extra field of cloze.

**Comment by c-okelly** [comment]
Hey,

Just tested in but something like this does work:

```org
* {{c1::Joe}} is a great man.
# type=Cloze
** Extra field
** [/path/to/image.jpg]

```

**Comment by michaelsjackson** [comment]
Can you tool allow also inline images, so nothing directly as header line definition, but as content?
Because the advantage of this style would be you could the those images directly in org-mode for example, you see again org-mode.  :smile: 
The usability would be much better, while designing your content you would always know and see the content, and not having to guess what was this image again.  The data would show itself already.

**Comment by c-okelly** [comment]
That is a really good point actually. I assume you're using org in Emacs?

**Comment by c-okelly** [comment]
I'm going to change add that as a feature request but should be easy enough to imply

**Comment by michaelsjackson** [comment]
Yes, org-mode in emacs.  Thanks for all the positive additions in future.

**Comment by michaelsjackson** [comment]
Tried now, the Extra line is even not necessary, it shows it in Extra field automatically great.  Not having the black dot (list element) before the image would be also nice, simpler view, but ok we should ignore this minor aspect and be happy it works at all.

```
* {{c1::Joe}} is a great man.
# type=Cloze
** [/path/to/image.jpg]

```
As you wrote main point is modifying a card is not possible, only adding a new one.  Having an option to modify later would be not bad, but one can not have everything it seems.

Defining a quick macro converting an inline image to org_to_anki version works nicely, as a transition solution.

**Comment by c-okelly** [comment]
I only added the extra line as an example of text. Probably should have been more clear. 

You can turn the bullet points off they are just on by default. There is more docs on it here:

https://github.com/c-okelly/org_to_anki/blob/master/documentation/orgReadme.md#html-list-types--list
