### ISSUE TITLE
Lists to Anki issue

### ISSUE THREAD

**Issue by lavalle17** [c-okelly/org_to_anki#77]
Hi, I really appreciate your contribution, i wish you can help me.

- [ Hey there it seems an error has occurred while running the importer:
the error was model was not found: basic. ] Error report provided by Anki
- [ windows 10] Operatin system
- [html ] Original file type
-the text has the same format you report in your instruction video.

**Comment by c-okelly** [comment]
Hey,

By any chance do you have Anki not setup in English?

The code looks for the basic model and if it isn't there would through that type of error.

If you added the basic model should work. Let me know

**Comment by lavalle17** [comment]
it is configured in spanish but i changed it and it works, thank you so much, im from chile, from the other side of the world, greetings.

**Comment by c-okelly** [comment]
Good to hear it is resolved. Grettings!
